demos/todomvc_on_rails/config/routes.rb
Todos::Application.routes.draw do
  resources :todos do
    member do
      post :toggle
    end

    collection do
      post :toggle_all
      get :active
      get :completed
      delete :destroy_completed
    end
  end

  root to: "todos#index"
end

demos/todomvc_on_rails/app/models/todo.rb
class Todo < ActiveRecord::Base
  scope :completed, -> { where("completed = ?", true) }
  scope :active, -> { where("completed = ?", false) }

  def title=(title)
    write_attribute(:title, title.strip)
  end
end

demos/todomvc_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demos/todomvc_on_rails/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  helper_method :current_filter

  def index
    @todos = Todo
  end

  def active
    @todos = Todo.active

    set_current_filter(:active)

    render :index
  end

  def completed
    @todos = Todo.completed

    set_current_filter(:completed)

    render :index
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
  end

  def destroy_completed
    @todos_for_destruction = Todo.completed.all
    
    Todo.completed.destroy_all
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
  end

  def toggle
    @todo = Todo.find(params[:id])
    @todo.toggle!(:completed)
  end

  def toggle_all
    Todo.update_all(completed: params[:completed] ? 't' : 'f')

    @todos = Todo.all
  end

private

  def todo_params
    params.require(:todo).permit(:title, :completed)
  end

  def set_current_filter(filter)
    @current_filter = filter
  end

  def current_filter
    @current_filter
  end
end

demos/todomvc_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

demos/todomvc_on_rails/app/helpers/todos_helper.rb
module TodosHelper
  def todos_filter_class
    "filtered " + current_filter.to_s
  end
end

demos/todomvc_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demos/todomvc_on_rails/app/views/layouts/todos.js.erb
<%= yield %>

$("#toggle-all").prop("checked", <%= Todo.active.count == 0 %>);

$("#todoapp").toggleClass("has_todos", <%= Todo.count > 0 %>);

$("#footer").replaceWith("<%= j(render("footer")) %>");

demos/todomvc_on_rails/app/views/todos/_destroy.js.erb
$("#<%= dom_id(todo) %>").remove();

demos/todomvc_on_rails/app/views/todos/_footer.html.erb
<footer id="footer">
  <span id="todo-count"><strong><%= Todo.active.count %></strong> <%= "item".pluralize(Todo.active.count) %> left</span>

  <ul id="filters">
    <li>
      <%= link_to "All", todos_path, class: "all" %>
    </li>
    <li>
      <%= link_to "Active", active_todos_path, class: "active" %>
    </li>
    <li>
      <%= link_to "Completed", completed_todos_path, class: "completed" %>
    </li>
  </ul>

  <% if Todo.completed.count > 0 %>
  <%= form_tag(destroy_completed_todos_path, method: :delete, remote: true) do %>
    <button id="clear-completed" type="submit">Clear completed (<%= Todo.completed.count %>)</button>
  <% end %>
  <% end %>
</footer>

demos/todomvc_on_rails/app/views/todos/_todo.html.erb
<li class="<%= "completed" if todo.completed? %>" id="<%= dom_id(todo) %>">
  <div class="view">
    <%= form_for(todo, url: toggle_todo_path(todo), method: :post, remote: true) do |f| %>
      <%= f.check_box :completed, class: "toggle", "data-behavior" => "submit_on_check" %>
    <% end %>
    <label data-behavior="todo_title"><%= todo.title %></label>
    <%= form_for(todo, method: :delete, remote: true) do |f| %>
      <button type="submit" class="destroy"></button>
    <% end %>
  </div>
  <%= form_for(todo, remote: true, html: { "data-behavior" => "edit_todo_form" }) do |f| %>
    <%= f.text_field :title, class: "edit", "data-behavior" => "todo_title_input", "data-original-value" => todo.title %>
  <% end %>
</li>

demos/todomvc_on_rails/app/views/todos/_toggle.js.erb
$("#<%= dom_id(todo) %>")
  .toggleClass("completed", <%= todo.completed? %>)
  .find("input.toggle")
  .prop("checked", <%= todo.completed? %>);

demos/todomvc_on_rails/app/views/todos/create.js.erb
$("#todo-list").append("<%= j(render(@todo)) %>");

$("#new-todo").val("");

demos/todomvc_on_rails/app/views/todos/destroy.js.erb
<%= render "destroy", todo: @todo %>

demos/todomvc_on_rails/app/views/todos/destroy_completed.js.erb
<%= render partial: "destroy", collection: @todos_for_destruction, as: :todo %>

demos/todomvc_on_rails/app/views/todos/index.html.erb
<section id="todoapp" class="<%= "has_todos" if @todos.unscoped.count > 0 %> <%= todos_filter_class %>">


  <header id="header">
    <h1>todos</h1>
    <%= form_for(Todo.new, remote: true) do |f| %>
      <%= f.text_field :title, placeholder: "What needs to be done?", id: "new-todo", autofocus: true, "data-behavior" => "submit_on_enter" %>
    <% end %>
  </header>


  <section id="main">
    <%= form_tag(toggle_all_todos_path, method: :post, remote: true) do %>
      <input name="completed" id="toggle-all" type="checkbox" value="true" data-behavior="submit_on_check" <%= "checked" if @todos.active.count == 0 %>>
    <% end %>
    <label for="toggle-all">Mark all as complete</label>
    <ul id="todo-list">
      <%= render @todos.all %>
    </ul>
  </section>


  <%= render "footer" %>


</section>


<footer id="info">
  <p>Double-click to edit a todo</p>
  <p>Created by <a href="mailto: smidwap@gmail.com">Matt De Leon</a></p>
  <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>

demos/todomvc_on_rails/app/views/todos/toggle.js.erb
<%= render "toggle", todo: @todo %>

demos/todomvc_on_rails/app/views/todos/toggle_all.js.erb
<%= render partial: "toggle", collection: @todos, as: :todo %>

demos/todomvc_on_rails/app/views/todos/update.js.erb
$("#<%= dom_id(@todo) %>").replaceWith("<%= j(render(@todo)) %>");